### PR TITLE
Updated freetype to 2.6.2

### PR DESCRIPTION
**Pull request by radarhere**

### CODE REVIEW

**Comment by hugovk** [comment]
I've merged https://github.com/python-pillow/pillow-wheels/pull/23 but don't have merge rights for this repo.

**Comment by wiredfool** [comment]
You should, as I moved this and added you all so that I didn't have to be the gatekeeper. Looks like the pillow team got added as read, not write access. I've changed that so you should be able to commit now.

**Comment by hugovk** [comment]
Thanks, merged now!

**Comment by wiredfool** [comment]
Oh Good.

**Pull request merged**
